server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery.server-addr: 127.0.0.1:8848
      #discovery.server-addr: 192.168.1.9:8849
management:
  endpoints:
    web:
      exposure:
        include: '*'