server:
  port: 80
spring:
  application:
    name: cloud-feign-payment-consumer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: PaymentConsummer80
    prefer-ip-address: true
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com:
      zja:
        springcloud:
          service:
            PaymentFeignService: debug
